
import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "../../components/navbar";
import ThemeProvider from "../../providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Jasir Basheer",
  description: "Generated by create next app",
  icons: {
    icon: "/jasirbasheer.jpg",
    apple: "/jasirbasheer.jpg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider>
          <div className="flex w-full min-h-screen">
            <Navbar />
            <main className="flex-1 h-screen overflow-y-auto">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
